---
version: "3.7"

services:
  pmm-server:
    image: percona/pmm-server:2.9.1
    container_name: pmm-server
    hostname: pmm-server
    ports:
      - 127.0.0.1:80:80
    environment:
      - DISABLE_UPDATES=1
      - METRICS_RESOLUTION_MR=5s
      # - PMM_DEBUG=1

  pmm-client:
    image: perconalab/pmm-client:2.9.1
    container_name: pmm-client
    hostname: pmm-client
    environment:
      - PMM_AGENT_SETUP=true
      - PMM_AGENT_SETUP_FORCE=true
      - PMM_AGENT_CONFIG_FILE=/usr/local/percona/pmm2/config/pmm-agent.yaml
      - PMM_AGENT_SERVER_ADDRESS=pmm-server:443
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      - PMM_AGENT_SERVER_INSECURE_TLS=true
      # - PMM_DEBUG=true
